version: '3.8'

services:
  jira-hub:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      # Mount for persistent temp files (optional)
      - ./temp_screenshots:/app/temp_screenshots
      # Mount for persistent settings (optional)
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (if you want to add it later)
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data

# volumes:
#   redis_data: 