version: '3.3'

services:
  # React Frontend Development Server
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true

  # Flask Backend API
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./scripts:/app/scripts
      - ./settings_manager.py:/app/settings_manager.py
      - ./set_jira_creds.sh:/app/set_jira_creds.sh
      - ./temp_screenshots:/app/temp_screenshots
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - PYTHONUNBUFFERED=1
      - PORT=5000
    env_file:
      - .env
    depends_on:
      - frontend-dev 